name: Cron 1 every hours

on:
  schedule:
    #0 */2 * * *
    - cron: "0 * * * *"

  workflow_dispatch:
    inputs:
      token:
        description: 'secret token'
        required: true

#concurrency: 
#  group: ${{ github.workflow }}-${{ github.ref }}
#  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
    - uses: actions/checkout@master
    
    - name: docker registry login
      run: echo "${{  secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}" | docker login ghcr.io --username admicro --password-stdin
      
    - name: Run cron
      if: success()
      run: |
        docker run \
        -e APP_NAME="${{ secrets.APP_NAME }}" \
        -e APP_TOKEN="${{ secrets.APP_TOKEN }}" \
        -e JOB_NAME="cron_rewrite" \
        -e JOB_ARG_1="" \
        -e TEST_SECRET="${{ github.event.inputs.token }}" \
        -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
        ghcr.io/admicro/ytbotserver-cli:latest
